<?php

namespace WDG\RestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BoppOrganisationManagementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoppOrganisationManagementRepository extends EntityRepository
{
}
