<?php

namespace WDG\RestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BoppProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoppProjectRepository extends EntityRepository
{
}
