#REDIRECTION VERS API
root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /api
        permanent: true

wdg_core_homepage:
    path:     /api
    defaults: { _controller: WDGCoreBundle:Default:index }

#API DOC
NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc

#REST 
wdg_core_rest : 
  type : rest 
  resource : "routing_rest.yml"
  prefix : /api