users : 
    type: rest
    resource:     "WDGCoreBundle:UserRest"
    name_prefix:  api_user_

projects : 
    type: rest
    resource:     "WDGCoreBundle:ProjectRest"
    name_prefix:  api_project_

projects_members:
    type:     rest
    parent:   projects
    resource: "WDGCoreBundle:ProjectsUsersRest"
    name_prefix:  api_project_users_

discussions:
    type:     rest
    parent:   projects
    resource: "WDGCoreBundle:DiscussionRest"
    name_prefix:  api_discussion_

organisations:
    type:     rest
    resource: "WDGCoreBundle:OrganisationRest"
    name_prefix:  api_organisation_

organisations_members:
    type:     rest
    parent:   organisations
    resource: "WDGCoreBundle:OrganisationsUsersRest"
    name_prefix:  api_organisations_users_

roles:
    type:     rest
    resource: "WDGCoreBundle:RoleRest"
    name_prefix:  api_roles_